### ISSUE TITLE
I guess you should also mentioned the source of the course.

### ISSUE THREAD

**Issue by pardeep3412** [Abhimanyu100/For-begineer#4]
I guess you're learning from "The Coding Train".
Is this the source [](url)
![screenshot_20180313-162626](https://user-images.githubusercontent.com/36933858/37337831-5edf499c-26ad-11e8-8815-5488437efee1.png)

**Comment by Abhimanyu100** [comment]
Yeah, indeed it is important to mention. I forget that.
Thanks Pardeep
